export const LESSON_ENGLISH: Record<string, string> = {
  // Elementary & Kinder English
  'Alphabet and Phonics': '<p class="text-slate-300 mb-6 leading-relaxed">The English alphabet has 26 letters. Phonics involves linking letters with their exact sounds.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> A makes the "ah" sound like in Apple!</li></ul></div>',
  'Reading and Comprehension': '<p class="text-slate-300 mb-6 leading-relaxed">Comprehension means understanding what a story is truly about, beyond just reading the words.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Important: Who is the main character? What is the main idea?</li></ul></div>',
  'Basic Vocabulary': '<p class="text-slate-300 mb-6 leading-relaxed">Vocabulary is the mental dictionary of words you know.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> A fast way to grow vocabulary is by reading lots of different books.</li></ul></div>',
  'Nursery Rhymes': '<p class="text-slate-300 mb-6 leading-relaxed">Short, rhyming poems designed for young children, like Humpty Dumpty.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> They teach rhythm and make learning memory fun!</li></ul></div>',
  'Simple Sentences': '<p class="text-slate-300 mb-6 leading-relaxed">A complete simple sentence has a Subject (who) and a Verb (action).</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> "The dog runs." (Subject: dog, Verb: runs).</li></ul></div>',
  'Parts of Speech': '<p class="text-slate-300 mb-6 leading-relaxed">Nouns are people/places/things. Verbs are action words. Adjectives describe nouns.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Example: The <strong class="text-blue-400">fast</strong> (adjective) <strong class="text-blue-400">car</strong> (noun) <strong class="text-blue-400">drove</strong> (verb).</li></ul></div>',
  'Essay Writing Basics': '<p class="text-slate-300 mb-6 leading-relaxed">A good essay has three main parts.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> An Introduction (hooks the reader), Body Paragraphs (the arguments), and a Conclusion.</li></ul></div>',
  'Vocabulary Building': '<p class="text-slate-300 mb-6 leading-relaxed">Learning prefixes (un-happy) and suffixes (happi-ness) allows you to unlock new meanings.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Synonyms are words with similar meanings (happy/joyful).</li></ul></div>',
  'Poetry and Stories': '<p class="text-slate-300 mb-6 leading-relaxed">Poetry focuses on rhythm and deep emotion, while Stories require characters, plots, and a setting.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Conflict is the core of any good story!</li></ul></div>',
  
  // High School English
  'Literary Analysis': '<p class="text-slate-300 mb-6 leading-relaxed">Analysis goes deeper than a summary. It asks *why* the author wrote a specific sentence or chose a specific theme.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> We look for metaphors, symbolism, and character arcs.</li></ul></div>',
  'Persuasive Essay Writing': '<p class="text-slate-300 mb-6 leading-relaxed">Persuasive essays aim to convince the reader using logical arguments, emotional appeals, and facts.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Always state your Thesis clearly in the first paragraph.</li></ul></div>',
  'World Literature': '<p class="text-slate-300 mb-6 leading-relaxed">Examines global literary masterpieces, contrasting the cultural themes found in European epics vs Asian folktales.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Great literature is a window into a culture\'s soul.</li></ul></div>',
  'Advanced Grammar': '<p class="text-slate-300 mb-6 leading-relaxed">Focuses on tricky mechanics: parallel structure, passive vs active voice, and complex dependent clauses.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Writing in the Active Voice makes prose punchier and easier to read.</li></ul></div>',
  'Public Speaking': '<p class="text-slate-300 mb-6 leading-relaxed">The art of delivering information loudly and confidently to a crowd without filler words (ums/ahs).</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Eye contact and hand gestures are as important as the script!</li></ul></div>',
  
  // Senior High English
  'Oral Communication': '<p class="text-slate-300 mb-6 leading-relaxed">Studies communication models (how sender and receiver interact) to avoid miscommunication.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Non-verbal cues (body language) account for over 50% of human communication.</li></ul></div>',
  'Reading and Writing Skills': '<p class="text-slate-300 mb-6 leading-relaxed">Prepares students for college-level critical reading. You learn to spot biases, logical fallacies, and authorial intent.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Teaches outlining and summarizing of complex journal articles.</li></ul></div>',
  'Academic & Professional English': '<p class="text-slate-300 mb-6 leading-relaxed">Strictly formal English writing. Covers the drafting of cover letters, resumes, and official company memos without slang.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Clarity, Brevity, and Professionalism are the 3 pillars.</li></ul></div>',
  '21st Century Literature': '<p class="text-slate-300 mb-6 leading-relaxed">Explores modern formats: graphic novels, spoken word poetry, blogs, speculative fiction, and hyper-poetry.</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Literature evolves alongside technology!</li></ul></div>',
  'Practical Research': '<p class="text-slate-300 mb-6 leading-relaxed">Students conduct real-world research by forming a hypothesis, gathering data, and writing a definitive research paper (Quantitative or Qualitative).</p><div class="bg-[#1c1c21] p-6 rounded-xl border border-white/5 mb-6"><ul class="space-y-3 mb-0 list-none pl-0 text-slate-300"><li class="flex items-start gap-3"><span class="text-blue-500">✓</span> Proper citation formatting (APA format) is strictly enforced to avoid plagiarism.</li></ul></div>'
};
